// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQ1j6947d8m2WVZNzosa2qFwdZDqnyGc',
    appId: '1:1019280216378:web:f02ea8db433f3c22054003',
    messagingSenderId: '1019280216378',
    projectId: 'movieapp-7ac09',
    authDomain: 'movieapp-7ac09.firebaseapp.com',
    storageBucket: 'movieapp-7ac09.firebasestorage.app',
    measurementId: 'G-0GFY0QR1LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLykFWkqKuQwFqzk9fZTEpBl7WptyXW0M',
    appId: '1:1019280216378:android:104dfb1e6bd861fc054003',
    messagingSenderId: '1019280216378',
    projectId: 'movieapp-7ac09',
    storageBucket: 'movieapp-7ac09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBniMe1Y5N4rBbIgItid0BW5XBP315aTLY',
    appId: '1:1019280216378:ios:14dcd5a7fc3a9b31054003',
    messagingSenderId: '1019280216378',
    projectId: 'movieapp-7ac09',
    storageBucket: 'movieapp-7ac09.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBniMe1Y5N4rBbIgItid0BW5XBP315aTLY',
    appId: '1:1019280216378:ios:14dcd5a7fc3a9b31054003',
    messagingSenderId: '1019280216378',
    projectId: 'movieapp-7ac09',
    storageBucket: 'movieapp-7ac09.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQ1j6947d8m2WVZNzosa2qFwdZDqnyGc',
    appId: '1:1019280216378:web:1b354a46fe3eebdf054003',
    messagingSenderId: '1019280216378',
    projectId: 'movieapp-7ac09',
    authDomain: 'movieapp-7ac09.firebaseapp.com',
    storageBucket: 'movieapp-7ac09.firebasestorage.app',
    measurementId: 'G-LY78VCK6TN',
  );
}
